FROM postgres:latest
LABEL "Project"="EvnHandle"
LABEL "Author"="tripqm"

ENV POSTGRES_DB="evnhandle"
ENV POSTGRES_USER="evnhandle"
ENV POSTGRES_PASSWORD="evnhandlepass"

#COPY init_db.sql /docker-entrypoint-initdb.d/init_db.sql
