version: '3.8'
services:
  evnsqldb:
    build: 
      context: ./db-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=evnsystempass
  
  evnpostgredb:
     build: 
      context: ./db-postgresql
     ports:
      - "5432:5432"
     volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  mysql: {}
  postgresql: {}